map ctrl+[ quit
map ctrl+n next 1
map ctrl+p next -1
map ctrl+d next 4
map ctrl+u next -4
map ctrl+f next 8
map ctrl+b next -8
map ctrl+j next 1
map ctrl+k next -1
map ctrl+h next left
map ctrl+l next right
