font_size 15.0
disable_ligatures always
scrollback_lines 200000
enable_audio_bell no
shell /usr/bin/fish

cursor none
cursor_text_color background

tab_bar_style           separator
tab_switch_strategy     right
tab_separator           "  "
tab_bar_background      #3c3836
active_tab_foreground   #8ec07c
active_tab_background   #3c3836
active_tab_font_style   normal
inactive_tab_foreground #7c6f64
inactive_tab_background #3c3836
inactive_tab_font_style normal

foreground            #ebdbb2
background            #1d2021
selection_foreground  none
selection_background  #665c54
color0                #665c54
color8                #928374
color1                #cc241d
color9                #fb4934
color2                #98971a
color10               #b8bb26
color3                #d79921
color11               #fabd2f
color4                #458588
color12               #83a598
color5                #b16286
color13               #d3869b
color6                #689d6a
color14               #8ec07c
color7                #ebdbb2
color15               #f9f5d7
url_color             #ebdbb2
active_border_color   #fe8019
inactive_border_color #3c3836
bell_border_color     #fb4934
mark1_foreground      #1d2021
mark1_background      #fabd2f
mark2_foreground      #1d2021
mark2_background      #fe8019
mark3_foreground      #1d2021
mark3_background      #d3869b

map kitty_mod+] next_tab
map kitty_mod+[ previous_tab
map --when-focus-on var:in_editor kitty_mod+/
map --when-focus-on var:in_editor kitty_mod+h
mouse_map left click ungrabbed mouse_handle_click selection prompt
