return {
	"aaronik/treewalker.nvim",
	cmd = { "Treewalker" },
	keys = {
		{
			"<C-h>",
			"<cmd>Treewalker Left<cr>",
			mode = { "n", "v" },
			noremap = true,
			silent = true,
			desc = "Moves to the first ancestor node that's on a different line from the current node",
		},
		{
			"<C-j>",
			"<cmd>Treewalker Down<cr>",
			mode = { "n", "v" },
			noremap = true,
			silent = true,
			desc = "Moves down to the next neighbor node",
		},
		{
			"<C-k>",
			"<cmd>Treewalker Up<cr>",
			mode = { "n", "v" },
			noremap = true,
			silent = true,
			desc = "Moves up to the previous neighbor node",
		},
		{
			"<C-l>",
			"<cmd>Treewalker Right<cr>",
			mode = { "n", "v" },
			noremap = true,
			silent = true,
			desc = "Moves to the next node down that's indented further than the current node",
		},
		{
			"<leader><",
			"<cmd>Treewalker SwapLeft<cr>",
			mode = "n",
			noremap = true,
			silent = true,
			desc = "Swap the node under the cursor with its previous neighbor",
		},
		{
			"]e",
			"<cmd>Treewalker SwapDown<cr>",
			mode = "n",
			noremap = true,
			silent = true,
			desc = "Swaps the biggest node on the line downward in the document",
		},
		{
			"[e",
			"<cmd>Treewalker SwapUp<cr>",
			mode = "n",
			noremap = true,
			silent = true,
			desc = "Swaps the highest node on the line upwards in the document",
		},
		{
			"<leader>>",
			"<cmd>Treewalker SwapRight<cr>",
			mode = "n",
			noremap = true,
			silent = true,
			desc = "Swap the node under the cursor with its next neighbor",
		},
	},
	opts = {
		highlight = false,
	},
}
