#!/bin/sh
set -eu

SRC="$1"
DEST="${1%.with_colors}"

if [ $SRC = $DEST ]; then
    echo '$1 does not have .with_colors suffix'
    exit 1
fi

GRUVBOX_DARK_DARK0_HARD="1d2021" \
GRUVBOX_DARK_DARK0="282828" \
GRUVBOX_DARK_DARK0_SOFT="32302f" \
GRUVBOX_DARK_DARK1="3c3836" \
GRUVBOX_DARK_DARK2="504945" \
GRUVBOX_DARK_DARK3="665c54" \
GRUVBOX_DARK_DARK4="7c6f64" \
GRUVBOX_DARK_LIGHT0_HARD="f9f5d7" \
GRUVBOX_DARK_LIGHT0="fbf1c7" \
GRUVBOX_DARK_LIGHT0_SOFT="f2e5bc" \
GRUVBOX_DARK_LIGHT1="ebdbb2" \
GRUVBOX_DARK_LIGHT2="d5c4a1" \
GRUVBOX_DARK_LIGHT3="bdae93" \
GRUVBOX_DARK_LIGHT4="a89984" \
GRUVBOX_DARK_BRIGHT_RED="fb4934" \
GRUVBOX_DARK_BRIGHT_GREEN="b8bb26" \
GRUVBOX_DARK_BRIGHT_YELLOW="fabd2f" \
GRUVBOX_DARK_BRIGHT_BLUE="83a598" \
GRUVBOX_DARK_BRIGHT_PURPLE="d3869b" \
GRUVBOX_DARK_BRIGHT_AQUA="8ec07c" \
GRUVBOX_DARK_BRIGHT_ORANGE="fe8019" \
GRUVBOX_DARK_NEUTRAL_RED="cc241d" \
GRUVBOX_DARK_NEUTRAL_GREEN="98971a" \
GRUVBOX_DARK_NEUTRAL_YELLOW="d79921" \
GRUVBOX_DARK_NEUTRAL_BLUE="458588" \
GRUVBOX_DARK_NEUTRAL_PURPLE="b16286" \
GRUVBOX_DARK_NEUTRAL_AQUA="689d6a" \
GRUVBOX_DARK_NEUTRAL_ORANGE="d65d0e" \
GRUVBOX_DARK_GRAY="928374" \
envsubst '$GRUVBOX_DARK_DARK0_HARD,$GRUVBOX_DARK_DARK0,$GRUVBOX_DARK_DARK0_SOFT,$GRUVBOX_DARK_DARK1,$GRUVBOX_DARK_DARK2,$GRUVBOX_DARK_DARK3,$GRUVBOX_DARK_DARK4,$GRUVBOX_DARK_LIGHT0_HARD,$GRUVBOX_DARK_LIGHT0,$GRUVBOX_DARK_LIGHT0_SOFT,$GRUVBOX_DARK_LIGHT1,$GRUVBOX_DARK_LIGHT2,$GRUVBOX_DARK_LIGHT3,$GRUVBOX_DARK_LIGHT4,$GRUVBOX_DARK_BRIGHT_RED,$GRUVBOX_DARK_BRIGHT_GREEN,$GRUVBOX_DARK_BRIGHT_YELLOW,$GRUVBOX_DARK_BRIGHT_BLUE,$GRUVBOX_DARK_BRIGHT_PURPLE,$GRUVBOX_DARK_BRIGHT_AQUA,$GRUVBOX_DARK_BRIGHT_ORANGE,$GRUVBOX_DARK_NEUTRAL_RED,$GRUVBOX_DARK_NEUTRAL_GREEN,$GRUVBOX_DARK_NEUTRAL_YELLOW,$GRUVBOX_DARK_NEUTRAL_BLUE,$GRUVBOX_DARK_NEUTRAL_PURPLE,$GRUVBOX_DARK_NEUTRAL_AQUA,$GRUVBOX_DARK_NEUTRAL_ORANGE,$GRUVBOX_DARK_GRAY' <"$SRC" >"$DEST"
